### ISSUE TITLE
Olog workflow did not insert timestamp

### ISSUE THREAD

**Issue by feigaoxyz** [pearcenuk/Alfred-public#3]
I'm trying your olog workflow but it did not insert the timestamp. do we need any plugin to support the `commandid=insert-current-time` part in the URI?

```
obsidian://advanced-uri?vault={var:vaultname}&daily=true&mode=append&commandid=insert-current-time
```

p.s. can we change the format of quick note? for example, I personally prefer the bullet style: `- (current_time) my notes or clipboard content`.  I assume we can use some template to fill in the user input and attach the payload as another parameter `&data=xxx` of obsidian uri ?

**Comment by feigaoxyz** [comment]
just notice your update to v1.4 that fixed the issue.

**Comment by pearcenuk** [comment]
Heya. Thanks for the comment. 
Yeah I didn't realise I was using another Obsidian thing that I should have called out in the requirements.

As for changing the format this is entirely in your hands as I decided to use a Clipboard paste block which you can update to your hearts content on how the output looks in Obsidian.

Thanks for trying it. 
Neil
