### ISSUE TITLE
README.md - Duplicate URL

### ISSUE THREAD

**Issue by pctony** [pearcenuk/Alfred-public#5]
hey, I see that the create and append URLs for Shortcuts is the same URL.  I suspect this is just a copy/paste thing - could you please share the append URL?

**Comment by pearcenuk** [comment]
Oh man, what a mistake to make. 

Thanks for picking that up. Git README, and Workflow info have been updated.

D'oh

**Comment by pctony** [comment]
Awesome, thanks for the fast fix! 



--
Cheers,
Tony

-----------------------
http://www.pc-tony.com
-----------------------
